services:
  app:
    image: mysociety/politician_data:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /workspaces/politician_data      
    volumes:
      - ./:/workspaces/politician_data/